INSERT INTO `role` (`roleid`, `rolename`, `rolememo`) VALUES (1, '管理员', '日常维护权限');
INSERT INTO `role` (`roleid`, `rolename`, `rolememo`) VALUES (2, '卖家', '可预览购买');
INSERT INTO `role` (`roleid`, `rolename`, `rolememo`) VALUES (3, '买家', '权限');
INSERT INTO `role` (`roleid`, `rolename`, `rolememo`) VALUES (4, '超级管理员', '最高权限');
INSERT INTO `role` (`roleid`, `rolename`, `rolememo`) VALUES (24, '纠错员', '纠正错误');
INSERT INTO `role` (`roleid`, `rolename`, `rolememo`) VALUES (25, '推销员', '产品推销');
INSERT INTO `role` (`roleid`, `rolename`, `rolememo`) VALUES (26, '运营人员', '平台运营');
INSERT INTO `role` (`roleid`, `rolename`, `rolememo`) VALUES (27, '编辑', '文案编辑');
INSERT INTO `role` (`roleid`, `rolename`, `rolememo`) VALUES (28, '采购', '产品进销');
